[package]
name = "handterm-client"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[features]
default = ["gpu"]
cpu = ["handterm/cpu"]
gpu = ["handterm/gpu"]
local-fonts = ["handterm/local-fonts"]
ligatures = ["handterm/ligatures"]
daemon-client = ["handterm/daemon-client"]

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
handterm = { path = "..", default-features = false, features = ["daemon-client"] }

[[bin]]
name = "handterm-client"
path = "src/main.rs"
