[package]
name = "handterm-server"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[features]
default = ["local-fonts", "ligatures"]
local-fonts = ["handterm/local-fonts"]
ligatures = ["handterm/ligatures"]
daemon-server = ["handterm/daemon-server"]

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
handterm = { path = "..", default-features = false, features = ["daemon-server"] }

[[bin]]
name = "handterm-server"
path = "src/main.rs"
